---
- name: Make sure config directory exists
  file:
    path: "{{ kubitect_cluster_config_path | dirname }}"
    state: directory
    mode: 0700

- name: Create a copy of the custom config file in a cluster directory
  copy:
    src: "{{ config_path }}"
    dest: "{{ kubitect_cluster_config_path }}"
    mode: 0600
  when:
    - config_path is defined
    - config_path != ""

- name: Make sure cluster config exists
  block:
    - name: Get stats of the current cluster config file
      stat:
        path: "{{ kubitect_cluster_config_path }}"
      register: cluster_config

    - name: Copy default config file if cluster config is missing
      copy:
        src: "{{ default.cluster_config_path }}"
        dest: "{{ kubitect_cluster_config_path }}"
        mode: 0600
      when:
        - cluster_config.stat.exists == false