---
- name: Include infrastructure config (tf output)
  include_vars:
    file: "{{ kubitect_cluster_path }}/config/infrastructure.yaml"
    name: infra

- name: Make sure config directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - ../../config/haproxy
    - ../../config/keepalived
    - ../../config/group_vars/all
    - ../../config/group_vars/k8s_cluster

- name: Generate HAProxy config
  template:
    src: ../../templates/haproxy/haproxy.cfg.j2
    dest: ../../config/haproxy/haproxy.cfg
  vars:
    loadbalancer_vip: "{{ infra.cluster.nodes.loadBalancer.vip }}"

- name: Generate Keepalived configurations
  template:
    src: ../../templates/keepalived/keepalived.cfg.j2
    dest: ../../config/keepalived/keepalived-{{ item.name }}.cfg
  vars:
    loadbalancer_vip: "{{ infra.cluster.nodes.loadBalancer.vip }}"
    network_interface: "{{ config.cluster.network.bridge if config.cluster.network.mode == 'bridge' else infra.cluster.nodeTemplate.os.networkInterface }}"
    priority: "{{ 201 - item.id }}"
  loop: "{{ infra.cluster.nodes.loadBalancer.instances }}"

- name: Generate Kubespray all.yaml
  template:
    src: ../../templates/kubespray/all.yaml.j2
    dest: ../../config/group_vars/all/all.yaml
    variable_start_string: "<<"
    variable_end_string: ">>"

- name: Generate Kubespray k8s_cluster.yaml
  template:
    src: ../../templates/kubespray/k8s_cluster.yaml.j2
    dest: ../../config/group_vars/k8s_cluster/k8s_cluster.yaml
    # Preserve Kubespray variables intact
    variable_start_string: "<<"
    variable_end_string: ">>"
    block_start_string: "<%"
    block_end_string: "%>"

- name: Generate Kubespray etcd.yaml
  template:
    src: ../../templates/kubespray/etcd.yaml.j2
    dest: ../../config/group_vars/etcd.yaml
    #dest: ../../config/group_vars/all/etcd.yaml

- name: Generate cluster's hosts.ini
  template:
    src: ../../templates/kubespray/hosts.ini.j2
    dest: ../../config/hosts.ini