---
- name: Fetch kubeconfig from first master node
  hosts: kube_control_plane[0]
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Fetch Kubeconfig
      fetch:
        src: "/etc/kubernetes/admin.conf"
        dest: "{{ config_dir }}/admin.conf"
        flat: true

- name: Finalize cluster deployment
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: false

  roles:
    - role: config/cluster/import

  tasks:
    - name: Change fetched Kubeconfig permissions
      file:
        path: "{{ config_dir }}/admin.conf"
        mode: 0600

    - name: Copy Kubeconfig
      block:
        - name: Make sure ~/.kube directory exists
          file:
            path: "~/.kube"
            state: directory

        - name: Copy kubeconfig file to a ~/.kube dirctory
          copy:
            src: "{{ config_dir }}/admin.conf"
            dest: "~/.kube/config"
            mode: 0600
      when:
        - config.kubernetes.other.copyKubeconfig is defined
        - config.kubernetes.other.copyKubeconfig == true

- name: Install addons
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  become: false

  pre_tasks:
    - name: Get system architecture fact
      setup:
        filter:
          - ansible_architecture

    - name: Resolve system architecture
      set_fact:
        arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

  roles:
    - role: config/cluster/import
    - role: config/infra/import
    - role: addons/helm
    - role: addons/rook
      when:
        - config.addons.rook.enabled is defined
        - config.addons.rook.enabled == true
