---
- name: Ensure SSH directory exists
  file:
    path: "{{ config_dir }}/.ssh"
    state: directory
    mode: 0700

- name: Check if private SSH key exists
  stat:
    path: "{{ config_dir }}/.ssh/id_rsa"
  register: ssh_key

- name: Check if public SSH key exists
  stat:
    path: "{{ config_dir }}/.ssh/id_rsa.pub"
  register: ssh_pub_key

- name: Generate SSH keys
  openssh_keypair:
    path: "{{ config_dir }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    mode: 0600
    force: true
  when:
    - not ssh_key.stat.exists or not ssh_pub_key.stat.exists
