---
# Commonly used directories
cluster_dir: "{{ playbook_dir }}/../.."
config_dir: "{{ cluster_dir }}/config"
bin_dir: "{{ cluster_dir }}/bin"

# Location where cluster config is saved
kubitect_cluster_config_path: "{{ config_dir }}/kubitect.yaml"
