---
- name: Ensure HAProxy is installed
  package:
    name: haproxy
    state: present

- name: Create HAProxy config
  vars:
    control_plane_instances: "{{ infra.nodes.master.instances }}"
    worker_instances: "{{ infra.nodes.worker.instances }}"
    forward_ports: "{{ config.cluster.nodes.loadBalancer.forwardPorts | default([]) }}"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    lstrip_blocks: true
  notify:
    - Restart HAProxy

- name: Start and enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: true
