---
- name: Get operating system ID
  raw: cat /etc/os-release | grep -i "^id="
  register: os_id
  changed_when: false

- name: Configure SELinux
  block:
    - name: Install python3 policy core utils
      yum:
        name: python3-policycoreutils
        state: present

    - name: Enable configured incoming ports
      vars:
        ports: "{{ config.cluster.nodes.loadBalancer.forwardPorts | map(attribute='port') | default([]) }}"
      seport:
        ports: "{{ ports | union([ 6443 ]) }}"
        proto: tcp
        setype: http_port_t
        state: present
  when:
    - ( "'centos' in os_id.stdout" ) or ( "'rocky' in os_id.stdout" )

- name: Allow binding non-local IP
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    state: present
    value: 1
    reload: true

- name: Setup Keepalived
  include_tasks: configure_keepalived.yaml

- name: Setup HAProxy
  include_tasks: configure_haproxy.yaml
