name: Release CLI Binaries

on:
  release:
    types: [ published ]

env:
  CLI_PATH: ./cli

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]  # Target systems,
        goarch: [ "386", amd64, arm64 ]   # with their architecture.
        exclude:
          # Exclude some combinations of system and architecture.
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.18
          binary_name: "tkk-cli"
          project_path: ${{ env.CLI_PATH }}
          extra_files: LICENSE  # Additional files to include with the binaries.