name: Test Deployment (Cluster)
run-name: "${{ github.ref_name }}: Test Deployment (Cluster)"

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-cluster:
    name: Cluster
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8sVersion:
          - v1.26.13
          - v1.27.10
          - v1.28.6
        distro:
          - ubuntu22
        networkPlugin:
          - calico

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/runner-setup

      - name: Deploy cluster
        run: |
          ./scripts/deploy-cluster.sh k8s \
            ${{ matrix.distro }} \
            ${{ matrix.networkPlugin }} \
            ${{ matrix.k8sVersion }}

      - name: Test
        run: |
          ./scripts/test-cluster.sh
